### ISSUE TITLE
Allocate all pkeys during initialization

### ISSUE THREAD

**Issue by ayrtonm** [immunant/IA2-Phase2#135]
We currently rely on Linux returning pkeys 1-N when we call `pkey_alloc`. This behavior is undocumented and we currently don't have a fallback if this doesn't happen. While Linux changing userspace is unlikely, it'd be good to have a fallback. To fix this we could allocate all 15 pkeys instead of just 1-N during initialization.

**Comment by rinon** [comment]
We pre-allocate all necessary pkeys as of 96234497d228fa2e995eed093ef8cd4d8e057bba. I don't think this issue is relevant any longer.

**Comment by fw-immunant** [comment]
This seems like it's describing a different concern than what's addressed by what we already do. It proposes allocating all 15 pkeys (in case they are returned in a different order than we expect), but we only allocate those we need, and abort if they are allocated in a different order than we expect.

This isn't a correctness concern, but is a (low-priority) possible future-proofing one.

**Comment by rinon** [comment]
We do assert that all the pkeys we get are what we expect in the right order. Why would we want to allocate more than we need?
