### ISSUE TITLE
Regressions from rebasing nginx

### ISSUE THREAD

**Issue by endbr64** [immunant/IA2-Phase2#155]
this work will mostly be happening on `nginx-rebase`

- [x] we are crashing trying to access the GOT again. does `padding.ld` need to come back in some form?
- [x] #160
- [x] `libia2/src/lib.rs` has a bunch of merge conflicts, but is no longer used. delete this on `main`, then rebase
- [x] verify that `ld --wrap` is working, particularly that the linker `.args` are passed to the right places
- [x] verify that the generated assembly changes were rebased/merged properly
- [x] merge the header rewriter include files change into `main`
- [ ] clean up the commit history
- [ ] grep the code for `nginx-rebase` for any other TODOs that this issue may be missing
- [x] fix the algorithm in `protect_pages()`, i think it currently fails when an ignore range overlaps a region exactly
- [ ] find a way to prevent Perl from touching `environ@@GLIBC_2.2.5` when reading environment variables (possibly override `getenv()`?)

**Comment by endbr64** [comment]
Used `git filter-branch --tree-filter 'mv examples external' nginx-rebase~25..HEAD` to rewrite our nginx path, seems to be working after rebase.

**Comment by ayrtonm** [comment]
We can still move some stuff from ia2.h to its source file, but #163 moved `protect_pages` which was what caused the issue during the rebase IIRC.

**Comment by endbr64** [comment]
Rebased on main, resolved issues due to the `ia2.h` split. `nginx` builds, but the worker process dies responding to the request. This is due to HTTP header filter code that lives in the main compartment, but is called from the Perl module. This is the same issue we were working on before the rebase.

**Comment by ayrtonm** [comment]
> This is due to HTTP header filter code that lives in the main compartment, but is called from the Perl module.

I believe we can fix this by using the same `--wrap` flags for the two shared objects that make up the perl module and call into nginx.

**Comment by endbr64** [comment]
I added the needed `--wrap` flags (and removed some extra ones, thanks Ayrton!). After some more debugging, `nginx` responds without crashing.

```
dmitriy@ubunut ~/g/I/e/nginx (nginx-rebase)> ./build/nginx
dmitriy@ubunut ~/g/I/e/nginx (nginx-rebase)> curl localhost:8001
hello from perl! my PID is 113713.
dmitriy@ubunut ~/g/I/e/nginx (nginx-rebase)> ps aux | rg nginx
dmitriy   113712  0.0  0.0  60640  1936 ?        Ss   22:25   0:00 nginx: master process ./build/nginx
dmitriy   113713  0.0  0.0  61080  4656 ?        S    22:25   0:00 nginx: worker process
dmitriy   113778  0.0  0.0   7708  5660 pts/0    S+   22:25   0:00 rg nginx
dmitriy@ubunut ~/g/I/e/nginx (nginx-rebase)> ./build/nginx -s quit
dmitriy@ubunut ~/g/I/e/nginx (nginx-rebase)> ps aux | rg nginx
dmitriy   113845  0.0  0.0   7708  5812 pts/0    S+   22:25   0:00 rg nginx
```

**Comment by endbr64** [comment]
I was wrong, I think my build was using an old cached `libia2.so` instead of the new C-only one. I'm currently working through some new issues that popped up with the actual `libia2`. There was a bug in the segment ignore algorithm, and now Perl is trying to access `environ@@GLIBC_2.2.5` which I'm trying to override.

**Comment by endbr64** [comment]
I still occasionally hit the `environ` issue. I think it is somehow caused by symbol versioning which is triggered by a certain compiler version. For instance, I can reproduce it on `donna` using:

```
mkdir build && cd build
cmake .. -DClang_DIR=/usr/lib/cmake/clang-13 -DLLVM_DIR=/usr/lib/llvm-13/cmake -DLLVM_EXTERNAL_LIT=`which lit` -DLIBIA2_INSECURE=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja
ninja check-ia2

cd ../external/nginx
```
change `--with-cc` line in the `reconfigure` script to point to `clang-13`
```
./reconfigure
make -j`nproc`

./build/nginx
```
The server won't start. `gdb` shows `[#0] Id 1, Name: "nginx", stopped 0x7ffff7cc8b89 in __GI_getenv (), reason: SIGSEGV`
