### ISSUE TITLE
Implement compartment-aware stack walkers for debuggers

### ISSUE THREAD

**Issue by endbr64** [immunant/IA2-Phase2#189]
Currently, our stack traces end when debuggers hit compartment transitions. This is because call gates change `ESP` to the new stack region and back.

GDB has frame filters, and LLDB has stack frame recognizers that can be used to implement custom stack walking.

**Comment by ayrtonm** [comment]
Do we need a special stack walker if we set the frame pointer correctly? Right now we just save rbp on the caller's stack, zero it out for the call then pop the old value. Instead we could save the old rbp on the caller's stack, set it to rsp right after we switch stacks then pop the old value after the call. I'm not sure how gdb chooses between frame pointers or eh_frame for unwinding, but making rbp a frame pointer in callgates should be fine regardless of whether other code is compiled with frame pointers or not.
