### ISSUE TITLE
Ensure that pkeys are allocated before calling `pkey_mprotect`

### ISSUE THREAD

**Issue by rinon** [immunant/IA2-Phase2#192]
If we don't allocate a pkey before using it in `pkey_mprotect`, the mprotect call will actually do nothing and we aren't really testing anything. This currently happens if `init_stacks` is called after `init_pkey_ctor` which is what appears to currently happen.

**Comment by fw-immunant** [comment]
What ordering causes this to happen? The two functions we have marked as constructors are `init_pkey_ctor` (in each compartment) and `init_stacks`, both of which begin with a call to `ensure_pkeys_allocated`.

**Comment by rinon** [comment]
Huh, I missed the call to ensure... so I think I may have mis-diagnosed this crash. I'm working on a branch so I'll try to repro on main.

**Comment by rinon** [comment]
Ohhhhh no, I completely mis-diagnosed this. We aren't actually setting up the main pkey before main. The real issue is #171, and I just exposed that by switching to compartment 0 (and not pkey 0 with full permissions) properly after protecting global data.
