### ISSUE TITLE
Ensure that static functions that have their address taken are not removed

### ISSUE THREAD

**Issue by ayrtonm** [immunant/IA2-Phase2#194]
When a static function has its address taken in a non-compartmentalized program, we create a call gate wrapper for it and assign the function pointer that address instead. This means that only the `call` instruction in the wrapper references the static function. Since the compiler treats asm statements as a black box, this allows it to remove the static function at compile-time even though the call gate references it.

This is an issue for the simple1, read_config and trusted_indirect tests and in PR #182 we worked around it by manually adding `__attribute__((used))` to those static functions. We should instead automatically add these attributes with the source rewriter (those source files have to be modified anyway since the call gate has to be defined in that translation unit).

Another option to consider would be some combination of `-fno-[tree-]dce/-femit-all-decls/-Wl,--no-gc-sections` for gcc/clang/ld. This may work but we have to check if `-fno-dce` works with `-O3` because [brief testing in #182](https://github.com/immunant/IA2-Phase2/pull/182#issuecomment-1496437554) seemed to show it didn't.

**Comment by ayrtonm** [comment]
yeah I thought about doing something similar to the statement in IA2_DEFINE_WRAPPER_foo idea (using it to initialize a `used` static pointer). I don't see a strong reason for not adding the used attribute on the function itself though, other than minimizing the diff made by the rewriter.

**Comment by ayrtonm** [comment]
For reference, this will require inserting a new `Replacement` in `file_replacements` in `FnPtrExpr::run` that prefixes `fn_decl` with `"__attribute__((used))"`. I'm not sure how this might interact with multiple decls, but for now it's easy enough to work around this in nginx by compiling with `-O0` so I'm not working on this for now.

**Comment by fw-immunant** [comment]
GCC docs state that attributes from multiple compatible declarations are merged, so we should be safe on that side: https://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html
