### ISSUE TITLE
Add support for C++ namespaces

### ISSUE THREAD

**Issue by ayrtonm** [immunant/IA2-Phase2#20]
We originally [considered various approaches](https://github.com/immunant/IA2-Phase2/pull/3#discussion_r706531870) to avoid duplicating function wrappers while still being able to support wrapping functions defined in C++ namespaces. The [current approach](https://github.com/immunant/IA2-Phase2/commit/a019ea7a872b94627984d23b7e7b0f57bb07bd2e) is to use track the mangled names of functions that have been wrapped instead of using the [canonical decl](https://clang.llvm.org/doxygen/classclang_1_1FunctionDecl.html#a45c66a41f3c45db795703a7ed5fd8953) (i.e. the first decl clang finds).

With this approach the header-rewriter correctly rewrites headers with functions in namespaces, but produces an invalid source wrapper. For example rewriting this header
```
#pragma once

namespace foo {
    int rand(void);
};

namespace bar {
    int rand(void);
};
```

produces this wrapper.c

```
int __ia2_rand() {
    int res = rand();
    return res;
}

int __ia2_rand() {
    int res = rand();
    return res;
}
```

**Comment by fw-immunant** [comment]
I think there are probably a lot of other C++-specific concerns that haven't been on our roadmap. This would just be a small part of C++ support which isn't a priority. Closing as not planned.
