### ISSUE TITLE
Enable repeated rewriter runs

### ISSUE THREAD

**Issue by ayrtonm** [immunant/IA2-Phase2#208]
We should make sure that the rewriter can be run repeatedly on a codebase without making changes each time. This would be useful to make sure the developer workflow with compartmentalized code isn't drastically different, but there are lots of open questions and issues.

# Rewriter changes
- when any of the rewriter passes change code will they match the new code in the next run? do different rewriter passes interact in this way?
-  do we update generated build artifacts in-place or overwrite them? can we minimize the diff if we overwrite check-in build artifacts
- need to check for [existing `used` attributes on static functions](https://github.com/immunant/IA2-Phase2/blob/main/header-rewriter/SourceRewriter.cpp#L494)
- make sure that adding a new function pointer type does not use an existing [function pointer ID](https://github.com/immunant/IA2-Phase2/blob/main/header-rewriter/SourceRewriter.cpp#L364-L370). Alternatively (and ideally), we'd get rid of function pointer IDs even if we keep the mangled types they correspond to
# Testing
This will be slightly cumbersome to test with cmake because the sources are compiled differently before the first rewriter run and afterwards (e.g. the rewriter generates a header which we need to `-include` to compile the code after the first run). We could either have separate targets for pre/post-rewriter sources or create an empty file to `-include` the generated header on the first run. The former seems more sane, but it would require two compile_commands.json because each source file would have two entries which libtooling does not really support well. Given the hacks required to get cmake to [generate a compile commands](https://github.com/immunant/IA2-Phase2/blob/main/cmake/define-test.cmake#L201-L205) we can use, I'm not sure how feasible it is to generate separate compile commands in cmake.

**Comment by ayrtonm** [comment]
Aside from ensuring that rewriter changes aren't duplicated, I also noticed that a second rewriter run doesn't pick up function pointer types that have already been turned into opaque structs. This means that the newly generated header will have missing types.

**Comment by ayrtonm** [comment]
Here are the parts of the rewriter that either rewrite or generate code. We should consider if they'll need changes and check them off as we validate that they work as expected with repeated runs.
- FnPtrTypes pass
    - [ ] function pointer types -> opaque structs
        - opaque structs are named based on mangled types not the IDs so repeated runs should be fine
- FnPtrNull
    - [ ] NULL function pointer expressions -> zeroed opaque structs
- FnPtrCall
    - [ ] generates IDs as it finds indirect callsite function signatures
        - we need to check what IDs were assigned in previous runs before we assign new ones
    - [ ] indirect callsites -> IA2_CALL(fn_ptr, ID)
        - should work if we use the same IDs that were previously assigned
        - need to check that AST matcher doesn't match existing `IA2_CALL` call
- FnPtrExpr
    - [ ] address-taken functions -> IA2_FN(fn_name)
    - [ ] used attribute for static address-taken functions
        - need to check for existing used attribute on address-taken functions
- FnPtrEq
    - [ ] opaque structs compared for equality or coerced to bool -> IA2_ADDR/IA2_FN_ADDR
- main
    - indirect callsite call gates (one per function signature not per callsite)
        - [ ] call gate asm in output .c
        - [ ] IA2_TYPE_$N in output .h
        - [ ] call gate declaration in output .h
    - function pointer types
        - [ ] opaque struct definitions in output .h
    - direct call gates
        - [ ] call gate asm in output .c
        - [ ] wrap command in linker-arg files
    - address-taken function call gates
        - external linkage
            - [ ] call gate declaration in output .h
            - [ ] call gate asm in output .c
        - static
            - [ ] call gate declaration in output .h
            - [ ] define IA2_DEFINE_WRAPPER_$FN_NAME in output .h
            - [ ] invoke IA2_DEFINE_WRAPPER_$FN_NAME in input .c

**Comment by ayrtonm** [comment]
Also as @rinon pointed out, to break the circular dependency between the rewriter's input (i.e. source files that `-include` the output header) and its output (the header it generates) we can have the rewriter create an empty output header if one doesn't already exist.

We might also need to do a similar thing for the linker-arg files, but this may require passing in the number of compartments as a separate required argument since we currently infer the number of compartments from the `-DPKEY` in the compile_commands.json.

**Comment by ayrtonm** [comment]
I have a WIP that adds `-include output_header.h` to targets unconditionally which lets us manually rerun the rewriter repeatedly on the sources that were copied to the build directory. This isn't too useful yet since we still need to test what happens when you make changes to the sources but it'd be good to merge the cmake changes for repeated runs before this. Since compile commands only supports one copy of each .c per JSON, instead of having multiple copies of the .c's in the build dir we can simulate changes with something like `-DPOST_REWRITER_CHANGES`. Then to run the rewriter a second time we'd pass in `--extra-arg=-DPOST_REWRITER_CHANGES` and to build the version with changes we'd have a separate cmake target that adds the define (note: this target would be omitted from the cc JSON just like the "wrapped" targets i.e. the first rewritten version).

**Comment by rinon** [comment]
I was thinking about this today, and I wonder if making the rewriter output sources to a different directory might avoid the whole issue. We don't want to operate on sources in-place most of the time IMO, and we could have an option that does if the user actually does, but in the normal case that would allow us to side-step this whole issue.

**Comment by ayrtonm** [comment]
> if making the rewriter output sources to a different directory might avoid the whole issue

We considered this before and if it were only source files that changed I might be in favor of having the rewriter output to a different directory. The problem is that headers make this more complicated since the list of headers that need to be copied is not explicitly passed in to the rewriter.

I do think we can avoid the `-DPOST_REWRITER_CHANGES` stuff though by copying sources and headers in cmake like we do for the first rewriter run. Instead of copying from the source dir to the build dir, cmake would copy from each test build dir to another build dir for each test and operate on the second copy. We'd also have to make the second rewriter run depend on the first to make sure that the second set of copies have the first set of annotations.

**Comment by ayrtonm** [comment]
Turns out getting two compile commands entries per test wasn't as clean as I was expecting, but I generated a JSON that should work with the rewriter. Basically instead of having three cmake targets (unmodified, first rewriter run and second run) we need one extra target per rewriter run so four in total. The extra target for the second run won't actually build with cmake because of differences in paths but that's also the case for the unmodified target we already have.

**Comment by rinon** [comment]
> The problem is that headers make this more complicated since the list of headers that need to be copied is not explicitly passed in to the rewriter.

No, but we have all headers available as we walk the AST. I think we would be able to copy everything from there, not the compile_commands.json. There's still the build files that need to be relocated, so we can't do everything in the rewriter, but I'd be more inclined towards this than trying to put a bunch of engineering effort into making it possible to re-run over already rewritten sources. It's extra complexity that we should avoid, if we can. Maybe we should have a call? There's probably still things I'm missing.

**Comment by ayrtonm** [comment]
> No, but we have all headers available as we walk the AST. I think we would be able to copy everything from there, not the compile_commands.json.

Yeah we definitely can, it's just extra complexity.

> I'd be more inclined towards this than trying to put a bunch of engineering effort into making it possible to re-run over already rewritten sources

Oh I thought you were proposing writing the output to a separate directory but still rerunning over the already rewritten sources. I think I understand what you had in mind, but we should talk through this because I'm not sure if this would actually work.
