### ISSUE TITLE
Define policy for syscalls manipulating memory mappings

### ISSUE THREAD

**Issue by fw-immunant** [immunant/IA2-Phase2#235]
We need to control access to the following syscalls that manipulate memory mappings:

`mmap`, `mremap`, `munmap`, `mprotect`, `pkey_mprotect`

**Comment by fw-immunant** [comment]
# 1. `mmap`

## Usage scenarios

We have at least (possibly, only) the following scenarios in which compartmentalized programs will use `mmap` (in roughly this order):

During program startup:
- in the dynamic loader mapping `ld.so.cache`
- in the dynamic loader for internal allocations
- in the dynamic loader when mapping segments of dynamic libraries
- in the dynamic loader allocating the TLS region

After program startup:
- inside the compartmentalized allocator to back allocations
- when allocating a thunk for our `pthread_create` wrapper
- directly in application or library code

## Threats

The threats posed by `mmap` to compartmentalization are:
1. `mmap` with the `MAP_FIXED` flag can overwrite existing mappings, changing their permissions and contents
2. newly-mapped memory can be accessed by any compartment, which can allow a compartment other than the one causing the allocation (for example, if running in another thread) to race to write into the newly-mapped region and corrupt it

## Mitigations

The latter of these cannot happen until after the program has started up enough to spawn new threads (i.e. main or constructors), so we don't need to guard against it when the dynamic loader is doing program startup.

To mitigate the first of these threats, we can forbid `MAP_FIXED` after program startup.

To mitigate the second, we need to:
- make sure the compartmentalized allocator follows a race-free sequence of an initial `mmap` with minimal permissions, followed by `mprotect`/`pkey_mprotect` to allow only the accesses we intend. If we can't avoid races here, we'll have to clear memory once we know it's in a state where only the desired compartment can write to it, prior to returning a pointer into the memory from the allocator.
- follow a similar protocol in the `pthread_create` wrapper
- wrap `mmap` calls from the application and libraries into a similar sequence of mapping and protection.

**Comment by fw-immunant** [comment]
# 2. `mremap`

## Usage scenarios

The only usage scenarios I know of for `mremap` are:
1. inside the compartmentalized allocator to resize one of its existing mappings
2. in application or library code to resize an existing allocation

## Threats

1. if one compartment `mremap`s a memory region used by another compartment, this can effectively remove that existing allocation. Either shrinking the region or moving it (with `MREMAP_MAYMOVE`) can result in addresses that were part of a region owned by the latter compartment now being unmapped. This would be a DoS, but it's worse: the former compartment can then map its own allocation in their place, even without `MAP_FIXED` (e.g. if it gets lucky and `MAP_ANONYMOUS` ends up there). This can effectively corrupt memory read by other compartments.
2. a compartment can use the `MREMAP_FIXED` flag to overwrite existing mappings; see the `MAP_FIXED` threat posed by `mmap`.

## Mitigations

To mitigate the first threat, we need to track the compartment that owns each memory mapping and forbid `mremap` of any addresses within another compartment's memory mappings. Any such tracking would need to be notified of calls to `mmap`, `mremap`, and `munmap` so it can follow the complete lifecycle of memory mappings, and would need to know which compartment is invoking them. We need to decide whether this tracking can be done in seccomp BPF or we need to defer to our userspace helper for it.

To mitigate the second threat, we can forbid the `MREMAP_FIXED` flag entirely. I don't think this is commonly used by any code we care about.

**Comment by fw-immunant** [comment]
# 3. `munmap`

I think this is just about entirely subsumed by the discussion of `mremap`. `munmap` has no flags, so it just needs to be constrained to the compartment that created the mapping. Implementation concerns are the same as for `mremap`.

**Comment by rinon** [comment]
> ## Mitigations
> 
> 
> 
> The latter of these cannot happen until after the program has started up enough to spawn new threads (i.e. main or constructors), so we don't need to guard against it when the dynamic loader is doing program startup.
> 
> 
> 
> To mitigate the first of these threats, we can forbid `MAP_FIXED` after program startup.

Many allocators use `MAP_FIXED` to allocate pages after reserving a region, so I don't know if we can realistically ban it. In fact, we can use it to prevent races if we can secure it - create a region but don't allocate pages, pkey_mprotect it, then do a fixed mapping into that region.


> To mitigate the second, we need to:
> 
> - make sure the compartmentalized allocator follows a race-free sequence of an initial `mmap` with minimal permissions, followed by `mprotect`/`pkey_mprotect` to allow only the accesses we intend. If we can't avoid races here, we'll have to clear memory once we know it's in a state where only the desired compartment can write to it, prior to returning a pointer into the memory from the allocator.
> 
> - follow a similar protocol in the `pthread_create` wrapper
> 
> - wrap `mmap` calls from the application and libraries into a similar sequence of mapping and protection.

**Comment by fw-immunant** [comment]
Closed by #290 with follow-ups in #293 and #295.
