### ISSUE TITLE
IA2_WRAP_FUNCTION does not work with bindgen

### ISSUE THREAD

**Issue by ahomescu** [immunant/IA2-Phase2#25]
Adding `IA2_WRAP_FUNCTION` to headers works fine when including the headers into C code, but not when converting them to Rust using bindgen because the tool ignores inline assembly.

**Comment by ayrtonm** [comment]
`IA2_WRAP_FUNCTION` was used to add `.symver` directives so I'm pretty sure this issue is obsolete.
