### ISSUE TITLE
Thread startup saves PKRU in spillable register across function calls

### ISSUE THREAD

**Issue by fw-immunant** [immunant/IA2-Phase2#257]
See `ALLOCATE_COMPARTMENT_STACK_AND_SETUP_TLS`. For each compartment, we save PKRU in `r12d`, change PKRU to the pkey for compartment, call `init_tls_N` for that compartment, then restore the PKRU from `r12d`.

The latter step can end up reading the wrong value if r12 is spilled to the stack and another thread in the same compartment writes to that memory before the register is unspilled. This can change what PKRU value the thread ends up running its main function with. The PKRU is then used to decide which compartment stack gets used for the thread, so a PKRU for the wrong compartment can/will not be noticed. A PKRU value that has pkeys for multiple compartments will get `NULL` back from `ia2_stackptr_for_pkru`, which will result in a null dereference and DoS, but one for another compartment will not.

**Comment by rinon** [comment]
I think compartment dispatch to a constant PKRU setter is the way to go here. I think we can write such a thing in assembly so that we can guarantee the PKRU value stays in registers until the control-flow branch.
