### ISSUE TITLE
Consider replacing ID parameter in `IA2_CALL` with mangled type names (again)

### ISSUE THREAD

**Issue by ayrtonm** [immunant/IA2-Phase2#326]
When we switched from rewriting headers to rewriting source files and headers (#182) we introduced a mapping from mangled type names to integer IDs `IA2_TYPE_N` generated by the rewriter. This was better than the status quo at the time since we were originally annotating files in-place so the `IA2_CALL` macros (and subsequently the mangled types) were all user-facing. After this PR the mangled types were replaced with an integer ID.

In #268 we switched from annotating in-place to annotating copies of the source files. This meant that most of the `IA2_CALL` macros only appeared in intermediate build files. In this PR we kept the `IA2_TYPE_N` IDs to minimize churn in the rewriter and to a lesser degree because there's still some value in keeping the intermediate build files readable. However since the IDs are assigned depending on the order that the rewriter encounters function pointer types this mapping is not fixed, meaning that different rewriter runs can produce different mappings. This ok when all `IA2_CALL`s are added by the rewriter but it just doesn't work when those macros need to be manually added to the original files. Somehow this wasn't an issue in nginx but it could be a problem if a function-like macro expands to something that needs to include `IA2_CALL`.

To fix this we should remove the IDs generated by the rewriter and replace them with mangled type names (again). This time degraded readability will be less of a concern since they'll mainly appear in intermediate sources. Another option is to try to remove the macro parameter completely like we tried in #222 (and reverted in #228) using `__builtin_choose_expr` and `__builtin_types_compatible_p`, but I don't remember how feasible this is.

**Comment by fw-immunant** [comment]
From today's meeting: another redundancy is `#define IA2_COMPARTMENT N` vs. `-DPKEY=N`; we should not require both.
