### ISSUE TITLE
`-DCMAKE_BUILD_TYPE` not propagated to `ia2-rewriter` and `pad-tls`

### ISSUE THREAD

**Issue by kkysen** [immunant/IA2-Phase2#375]
Building with `cmake -DCMAKE_BUILD_TYPE=Debug` should build with debug info, and does for all of the binaries except for `ia2-rewriter` and `pad-tls`.  I think this is because they are invoked with `cmake --build` instead of as normal dependencies/subdirectories.

**Comment by kkysen** [comment]
Building the tools this way also means `ninja tools` doesn't rebuild anything after modifying its sources; only a full `ninja` does, but that builds and runs a bunch of other stuff that takes longer to build.  @fw-immunant, what was the reason it's done this way?  I remember you said there was some reason.  Do you know how to get around it?

**Comment by kkysen** [comment]
I tried adding `--config ${CMAKE_BUILD_TYPE}` after the `cmake --build`, but that still doesn't seem to work.

**Comment by fw-immunant** [comment]
Ah, I have a stashed hunk that adds `
-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}` to our `ExternalProject_Add`
invocation.

The reason things are this way is to compile the tools natively even when
cross-compiling the rest of the project for ARM, but it also causes a bunch
of problems. Maybe we can find a different way to compile host tools.

[This thread](
https://discourse.cmake.org/t/building-compile-time-tools-when-cross-compiling/601/11)
seems to suggest the way we're doing things, but it really doesn't work
*well*...

The CMake docs suggest an alternative strategy that involves invoking the
build multiple times, which is also really ugly:
https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html#cross-compiling-a-complex-project-vtk

**Comment by fw-immunant** [comment]
Ah, I have a stashed hunk that adds `-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}` to our `ExternalProject_Add`
invocation.

The reason things are this way is to compile the tools natively even when
cross-compiling the rest of the project for ARM, but it also causes a bunch
of problems. Maybe we can find a different way to compile host tools.

[This thread](https://discourse.cmake.org/t/building-compile-time-tools-when-cross-compiling/601/11)
seems to suggest the way we're doing things, but it really doesn't work *well*...

The CMake docs suggest an alternative strategy that involves invoking the
build multiple times, which is also really ugly:
https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html#cross-compiling-a-complex-project-vtk
