### ISSUE TITLE
rewriter: `assert(comp_cmds.size() == 1)` fails on templated files like in `dav1d`

### ISSUE THREAD

**Issue by kkysen** [immunant/IA2-Phase2#393]
`dav1d` uses templated source files that are compiled multiple times, but `ia2-rewriter` currently has an `assert(comp_cmds.size() == 1)`.  It might be good enough to just turn this into a warning instead and run things on the first compile command.

**Comment by rinon** [comment]
That or build with a single bit depth, run the rewriter with that compile commands, then rebuild the rewritten sources with both bit depths. I think that'd be better here, because this is an unusual case. We can make it a warning but I'm afraid it'll get lost in the noise.
