### ISSUE TITLE
Using a relative path for `--root-directory` breaks rewriter file copies

### ISSUE THREAD

**Issue by randomPoison** [immunant/IA2-Phase2#408]
For zlib the source files are directly at the root of the checkout, which means the value I want to pass to `--root-directory` is `.`. But if I run the rewriter and do `--root-directory=.` then the rewriter fails to copy the source files into the build directory. If I instead use the absolute path to the current directory, then the rewriter correctly copies the source files.

**Comment by kkysen** [comment]
We can just fix this by making the path absolute right away, right?

**Comment by randomPoison** [comment]
Almost certainly, that's what I'm assuming the fix is.
