### ISSUE TITLE
Document missing build steps

### ISSUE THREAD

**Issue by randomPoison** [immunant/IA2-Phase2#409]
In integrating IA2 into zlib I uncovered a number of build steps that aren't currently covered in the docs. We'll need to update the docs to include the following:

* [x] How to run the rewriter, i.e. source changes, compiler args, and rewriter args.
* [x] [`partition-alloc`](https://github.com/immunant/IA2-Phase2/tree/main/runtime/partition-alloc) needs to be included in the final containerized build, and the `--wrap=malloc` linker args need to be added.
* [x] Either `LIBIA2_X86_64` or `LIBIA2_ARM64` defines need to be set for the containerized build.
* [x] Run `pad-tls` on any shared objects that use TLS. We probably also want to document how to determine if a `.so` uses TLS.

**Comment by kkysen** [comment]
> Either `LIBIA2_X86_64` or `LIBIA2_ARM64` defines need to be set for the containerized build.

This is fixed as of #400.

**Comment by ayrtonm** [comment]
> We probably also want to document how to determine if a .so uses TLS.

We were thinking about adding runtime checks for this in #404, so we can also point users to the right `readelf` flags in that error message.

**Comment by ayrtonm** [comment]
> [partition-alloc](https://github.com/immunant/IA2-Phase2/tree/main/runtime/partition-alloc) needs to be included in the final containerized build, and the --wrap=malloc linker args need to be added.

It might be a good idea to runtime checks for this as well.

**Comment by ayrtonm** [comment]
The names of `-DIA2_DEBUG` and `-DIA2_DEBUG_LOG` are also too similar. After addressing #452 the former will probably be `-DIA2_RELEASE` with inverted semantics and we should consider renaming the former to something like `-DIA2_VERBOSE` or `-DIA2_LOG` since that seems more descriptive than "debug".

**Comment by kkysen** [comment]
> The names of `-DIA2_DEBUG` and `-DIA2_DEBUG_LOG` are also too similar. After addressing #452 the former will probably be `-DIA2_RELEASE` with inverted semantics and we should consider renaming the former to something like `-DIA2_VERBOSE` or `-DIA2_LOG` since that seems more descriptive than "debug".

`-DIA2_VERBOSE` sounds good to me.
