### ISSUE TITLE
rewriter: callbacks to other libraries (e.x. `pthread`, `libc`) are rewritten

### ISSUE THREAD

**Issue by kkysen** [immunant/IA2-Phase2#427]
Callbacks to other libraries (e.x. `pthread` with `pthread_once`, `pthread_create`, etc.) are rewritten with `IA2_FN`, but this doesn't work because these functions are not and can't be rewritten since they're part of another dynamically linked binary library.

For example,

```diff
diff --git a/src/lib.c b/src/lib.c
index 4d9a2d3..35ae3aa 100644
--- a/src/lib.c
+++ b/src/lib.c
@@ -140 +140 @@ COLD int dav1d_open(Dav1dContext **const c_out, const Dav1dSettings *const s) {
-    pthread_once(&initted, init_internal);
+    pthread_once(&initted, IA2_FN(init_internal));
@@ -280 +280 @@ COLD int dav1d_open(Dav1dContext **const c_out, const Dav1dSettings *const s) {
-            if (pthread_create(&t->task_thread.td.thread, &thread_attr, dav1d_worker_task, t)) {
+            if (pthread_create(&t->task_thread.td.thread, &thread_attr, IA2_FN(dav1d_worker_task), t)) {
```

This results in an error because the call is now wrong.

I'm also getting other errors here, of the `IA2_fnptr_*` for `__ia2_dav1d_worker_task` and `__ia2_init_internal` not being defined.  I'm not really sure if that's related, or if some other error is masking that.

Another different kind of example is in calling `signal` or `sigaction` with `struct sigaction`'s `.sa_handler` field.  The signal handler is wrapped with `IA2_FN`, but the existing signature doesn't allow this.

**Comment by ayrtonm** [comment]
Interaction with system header callbacks is a known issue where you have to manually add `IA2_IGNORE`. https://github.com/immunant/IA2-Phase2/blob/main/docs/usage.md#interaction-with-system-headers

Signal handlers cause a similar compiler error, but they are supported. I just didn't document `IA2_SIGHANDLER` in the usage doc. https://github.com/immunant/IA2-Phase2/blob/main/runtime/libia2/include/ia2.h#L52
