### ISSUE TITLE
`fake_criterion_tests` iteration is broken due to padding

### ISSUE THREAD

**Issue by kkysen** [immunant/IA2-Phase2#473]
When trying to add multiple `Test`s in a single executable, I discovered that only the first test was actually being run.  `fake_criterion` currently works by putting all of the `fake_criterion_test`s into the same section, `fake_criterion_tests`, and then iterating over the `fake_criterion_test`s in this section by using the generated symbols `__start_fake_criterion_tests` and `__stop_fake_criterion_tests`.  However, it seems there is now padding between these test elements, so the `++` on the `const fake_criterion_test*` pointer is incorrectly iterating over them.  The padding is zeroed, and so the function pointer null check fails, and the loop exits early.  I'm not sure how the rules work for multiple objects in a section (like if they're the same or different from a C array).

Another potential solution instead of putting all of the test `struct`s into the same section is generate `__attribute__((constructor))` functions that add the test `struct` to a list.  This is how trusty does it, for example: https://android.googlesource.com/trusty/lk/trusty/+/refs/heads/main/include/shared/lk/trusty_unittest.h#323.  However, we'd have to make sure this doesn't interfere with any `__attribute__((constructor))`s used by IA2.

**Comment by ayrtonm** [comment]
I think the constructor approach should be fine even though it may be interleaved with compartment initialization constructors. There's a way to assign constructor priorities but it only applies for those within a DSO so I don't think it adds much.

The only thing we need to be careful with is making sure that memory accesses within the constructor adding the tests only touch shared data. The constructor order will probably be library initialization, then main binary initialization and test constructors. The order of the latter two is hard to guess. This happens before initializing the PKRU/compartment stack though so the test constructors have to assume they can only access shared data.
