### ISSUE TITLE
Blacklisting headers from being rewritten with .gitignore-like file

### ISSUE THREAD

**Issue by ayrtonm** [immunant/IA2-Phase2#6]
Public library headers may include functions declared in private and system headers. Since we only want to wrap functions defined in the library, we need a way to differentiate between private and system headers.

We currently plan on using the header's path to do this by blacklisting everything in `/usr/include/` and wrapping everything else. A better long-term solution would be to have a .gitignore-like file for blacklisting directories and files from being rewritten.

**Comment by rinon** [comment]
Do we still need this now that we're not really re-writing headers? We're not planning to copy anything outside the source root directory, so system headers will be ignored automatically?

**Comment by ayrtonm** [comment]
We're still rewriting headers but the rewriter now requires a `--root-directory` argument which we use to determine if a header should be modified or not.
