### ISSUE TITLE
Phase 2 Roadmap

### ISSUE THREAD

**Issue by ahomescu** [immunant/IA2-Phase2#9]
- [ ] #12
- [ ] #13
- [ ] #14
- [x] #11
- [x] #16
- [ ] #10
- [x] #17
- [ ] #15
- [ ] #18
- [ ] Triage and fix issues

If there are more items to add, mention them in a comment.

**Comment by rinon** [comment]
Tracked in [Projects - IA2 Phase 2](https://github.com/orgs/immunant/projects/2) now.
